### ISSUE TITLE
Docker container can only start successfully on the first start, fails on subsequent restarts

### ISSUE THREAD

**Issue by Neurrone** [dgsb/docker-ikiwiki#3]
I'm running the image using a simple docker-compose file:

```
version: '2'
services:
  ikiwiki:
    image: 'dgsb/ikiwiki'
    ports:
      - '2222:22'
      - '8080:80'
    volumes:
      - './data:/wiki'
```

It starts fine the first time when I do docker-compose up. But when trying to start the container after shutting it down, I always get the following error:

```
> docker-compose up
Starting ikiwiki_ikiwiki_1 ... done                                                                                                                                         Attaching to ikiwiki_ikiwiki_1
ikiwiki_1  | /
ikiwiki_1  | fatal: destination path '/var/www/wiki.git' already exists and is not an empty directory.
ikiwiki_ikiwiki_1 exited with code 128
```
